[[headers]]
  for = "/"
  [headers.values]
    Content-Type = "text/xml"

[[headers]]
  for = "/index.xml"
  [headers.values]
    Content-Type = "text/xml"

[[headers]]
  for = "/assets/style.xsl"
  [headers.value]
    Content-Type = "text/xml"

[[redirects]]
  from = "/"
  to = "/index.xml"
  status = 200
  force = true

